services:
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
  worker:
    build: 
      context: ./app
      dockerfile: Dockerfile.worker
    depends_on:
      redis:
        condition: service_healthy
  
